redis:
  host: localhost
  port: 6379
  namespace: bg_

full_articles:
  path: /Users/iros/dev/bocoup/opengendertracking/bostonglobe_articles

storeType: MongoStore

FileSystemStore:
  articles:
    path: data/articles
  jobs:
    path: data/jobs

MongoStore:
  mongo:
    host: localhost
    port: 27000