redis:
  host: localhost
  port: 6379
  namespace: bg_

storeType: MongoStore

FileSystemStore:
  articles:
    path: data/articles
  jobs:
    path: data/jobs

MongoStore:
  mongo:
    host: localhost
    port: 27000